import type { Metadata } from "next";
import Link from "next/link";
import { getPublicBuildsMode } from "@/lib/public-builds/constants";
import { PublicPage, PublicNext } from "../components/public-page";
export const metadata: Metadata = { title: "How it works — Trajectas", description: "From a position description to relevant capabilities, an assessment and a report.", alternates: { canonical: "/how-it-works" } };
const steps = [
  ["Start with the work", "Enter a role title and paste or upload a position description. Responsibilities, working context and the decisions the role needs to make give the matching process useful evidence.", "You verify your email before the description is processed."],
  ["Review what the role calls for", "Trajectas matches the description to capabilities in the assessment library. Review the role interpretation and the explanation behind each recommendation, then adjust the selection.", "Choose 4–8 capabilities. Each adds six questions; the question count and estimated time update before you continue."],
  ["Take the assessment", "Create your assessment and open your personal link. The free Role Builder is a one-person experience so you can try the questions yourself.", "The link is also sent by email. A typical six-capability assessment has 36 questions and takes about seven minutes."],
  ["Read your report", "After you finish, explore the report in the assessment experience and receive it by email. Use it to understand the capabilities covered and start a more informed conversation.", "For assessment programmes involving your team or clients, contact us to discuss the wider workflow."],
];
export default function Page() { return <PublicPage label="How it works" title="From the role to a clearer picture." intro="A position description sets the context. You review the recommendations before an assessment is created."><div className="px-container px-explainer">{getPublicBuildsMode() === "closed" && <p className="rb-note">Role Builder is invitation-only during preview. <Link href="/contact?topic=invitation">Ask for an invitation.</Link></p>}{steps.map(([title, body, note], index) => <section key={title}><span className="px-explainer-index">0{index + 1}</span><div><h2>{title}</h2><p>{body}</p><p className="px-explainer-note">{note}</p></div></section>)}</div><section className="px-process"><div className="px-container px-reading"><h2>What is a capability?</h2><p>A capability describes how someone approaches a kind of work: making judgements, planning delivery or collaborating with others, for example. Its relevance depends on the role and its context.</p><p>The matching explanation shows why a capability may matter for the role. It is a recommendation to review, not an assessment of the person doing the job.</p><Link className="px-light-link" href="/capability-model">Explore the capability model</Link></div></section><PublicNext /></PublicPage>; }
