import type { Metadata } from "next";
import Link from "next/link";
import { PublicPage, PublicNext } from "../components/public-page";
export const metadata: Metadata = { title: "How Trajectas works — Context, capability and evidence", description: "See how Trajectas connects role context, capability assessment and reporting to selection and development decisions.", alternates: { canonical: "/how-it-works" } };
const steps = [
  ["Define the decision and its context", "Start with what you need to understand: selecting for a role, supporting a transition or focusing development. The work, its responsibilities and its challenges establish the context.", "Role descriptions are one starting point. For wider programmes, we begin with the people decisions and outcomes you want to support."],
  ["Bring the relevant capabilities into focus", "Build a shared view of the capabilities that matter. Clear definitions and behavioural indicators make the model easier to discuss, challenge and apply to real work.", "Role Builder offers recommendations from a position description. You review the interpretation and capability choices before creating an assessment."],
  ["Gather evidence through assessment", "Participants complete an assessment through a personal link. The selected capabilities shape what is measured; reporting brings the resulting evidence together.", "The public Role Builder is a one-person introduction. Organisation and partner programmes have their own participant delivery workflows."],
  ["Use the evidence in the conversation", "Interpret the results alongside the role and other evidence. Use that understanding to focus selection questions, identify development priorities or revisit progress over time.", "Assessment informs a decision. Human judgement, context and a clear purpose remain essential to how the results are used."],
];
export default function Page() { return <PublicPage label="How the platform works" title="Context first. Evidence with purpose." intro="A connected approach to understanding capability — from the work people need to do to the decisions you need to make."><div className="px-container px-explainer">{steps.map(([title, body, note], index) => <section key={title}><span className="px-explainer-index">0{index + 1}</span><div><h2>{title}</h2><p>{body}</p><p className="px-explainer-note">{note}</p></div></section>)}</div><section className="px-process"><div className="px-container px-reading"><h2>A shared language for capability.</h2><p>The capability model gives different roles and programmes a common reference point. Definitions describe the capability; behavioural indicators make its expression more concrete.</p><p>Its relevance still depends on context. A recommendation about a role is separate from the evidence gathered about a person.</p><Link className="px-light-link" href="/capability-model">Explore the capability model</Link></div></section><PublicNext /></PublicPage>; }
